/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Graph {
  nodes: (InputNode | Conv2DNode | LinearNode | ReLUNode | MaxPool2DNode | FlattenNode)[];
  edges?: Edge[];
  train?: TrainConfig;
}
export interface InputNode {
  id: string;
  type: "input";
  shape: number[];
}
export interface Conv2DNode {
  id: string;
  type: "conv2d";
  out_channels: number;
  kernel_size?: number;
  stride?: number;
  padding?: number;
}
export interface LinearNode {
  id: string;
  type: "linear";
  out_features: number;
}
export interface ReLUNode {
  id: string;
  type: "relu";
}
export interface MaxPool2DNode {
  id: string;
  type: "maxpool2d";
  kernel_size?: number;
  stride?: number | null;
}
export interface FlattenNode {
  id: string;
  type: "flatten";
}
export interface Edge {
  src: string;
  dst: string;
}
export interface TrainConfig {
  dataset?: "mnist";
  epochs?: number;
  batch_size?: number;
  lr?: number;
}
